// generated by deep-copy -o nal_deepcopy.go --type NAL .; DO NOT EDIT.

package h264parse

// DeepCopy generates a deep copy of NAL
func (o NAL) DeepCopy() NAL {
	var cp NAL = o
	if o.RBSPByte != nil {
		cp.RBSPByte = make([]byte, len(o.RBSPByte))
		copy(cp.RBSPByte, o.RBSPByte)
	}
	if o.HeaderBytes != nil {
		cp.HeaderBytes = make([]byte, len(o.HeaderBytes))
		copy(cp.HeaderBytes, o.HeaderBytes)
	}
	cp.SPS = o.SPS.DeepCopy()
	cp.PPS = o.PPS.DeepCopy()
	cp.SEI = o.SEI.DeepCopy()
	if o.VUI.NALHRDParameters.AlternativeCPBSpecifications != nil {
		cp.VUI.NALHRDParameters.AlternativeCPBSpecifications = make([]AlternativeCPBSpecification, len(o.VUI.NALHRDParameters.AlternativeCPBSpecifications))
		copy(cp.VUI.NALHRDParameters.AlternativeCPBSpecifications, o.VUI.NALHRDParameters.AlternativeCPBSpecifications)
	}
	if o.VUI.VCLHRDParameters.AlternativeCPBSpecifications != nil {
		cp.VUI.VCLHRDParameters.AlternativeCPBSpecifications = make([]AlternativeCPBSpecification, len(o.VUI.VCLHRDParameters.AlternativeCPBSpecifications))
		copy(cp.VUI.VCLHRDParameters.AlternativeCPBSpecifications, o.VUI.VCLHRDParameters.AlternativeCPBSpecifications)
	}
	return cp
}
