// Code generated by "stringer -type=NALUnitType"; DO NOT EDIT.

package h264parse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unspecified0-0]
	_ = x[CodedSliceNonIDRPicture-1]
	_ = x[CodedSliceDataPartitionA-2]
	_ = x[CodedSliceDataPartitionB-3]
	_ = x[CodedSliceDataPartitionC-4]
	_ = x[CodedSliceIDRPicture-5]
	_ = x[SupplementalEnhancementInformation-6]
	_ = x[SequenceParameterSet-7]
	_ = x[PictureParameterSet-8]
	_ = x[AccessUnitDelimiter-9]
	_ = x[EndOfSequence-10]
	_ = x[EndOfStream-11]
	_ = x[FillerData-12]
	_ = x[SequenceParameterSetExtension-13]
	_ = x[PrefixNALUnit-14]
	_ = x[SubsetSequenceParameterSet-15]
	_ = x[DepthParameterSet-16]
	_ = x[Reserved17-17]
	_ = x[Reserved18-18]
	_ = x[CodedSliceAuxiliaryCodedPictureWithoutPartitioning-19]
	_ = x[CodedSliceExtension-20]
	_ = x[CodedSliceExtensionDepthViewComponentOr3DAVCTextureView-21]
	_ = x[Reserved22-22]
	_ = x[Reserved23-23]
	_ = x[Unspecified24-24]
	_ = x[Unspecified25-25]
	_ = x[Unspecified26-26]
	_ = x[Unspecified27-27]
	_ = x[Unspecified28-28]
	_ = x[Unspecified29-29]
	_ = x[Unspecified30-30]
	_ = x[Unspecified31-31]
}

const _NALUnitType_name = "Unspecified0CodedSliceNonIDRPictureCodedSliceDataPartitionACodedSliceDataPartitionBCodedSliceDataPartitionCCodedSliceIDRPictureSupplementalEnhancementInformationSequenceParameterSetPictureParameterSetAccessUnitDelimiterEndOfSequenceEndOfStreamFillerDataSequenceParameterSetExtensionPrefixNALUnitSubsetSequenceParameterSetDepthParameterSetReserved17Reserved18CodedSliceAuxiliaryCodedPictureWithoutPartitioningCodedSliceExtensionCodedSliceExtensionDepthViewComponentOr3DAVCTextureViewReserved22Reserved23Unspecified24Unspecified25Unspecified26Unspecified27Unspecified28Unspecified29Unspecified30Unspecified31"

var _NALUnitType_index = [...]uint16{0, 12, 35, 59, 83, 107, 127, 161, 181, 200, 219, 232, 243, 253, 282, 295, 321, 338, 348, 358, 408, 427, 482, 492, 502, 515, 528, 541, 554, 567, 580, 593, 606}

func (i NALUnitType) String() string {
	if i >= NALUnitType(len(_NALUnitType_index)-1) {
		return "NALUnitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NALUnitType_name[_NALUnitType_index[i]:_NALUnitType_index[i+1]]
}
