// generated by deep-copy -o pps_deepcopy.go --type PPS .; DO NOT EDIT.

package h264parse

// DeepCopy generates a deep copy of PPS
func (o PPS) DeepCopy() PPS {
	var cp PPS = o
	if o.RunLengthMinus1 != nil {
		cp.RunLengthMinus1 = make([]uint64, len(o.RunLengthMinus1))
		copy(cp.RunLengthMinus1, o.RunLengthMinus1)
	}
	if o.TopLeft != nil {
		cp.TopLeft = make([]uint64, len(o.TopLeft))
		copy(cp.TopLeft, o.TopLeft)
	}
	if o.BottomRight != nil {
		cp.BottomRight = make([]uint64, len(o.BottomRight))
		copy(cp.BottomRight, o.BottomRight)
	}
	if o.SeqScalingListPresentFlags != nil {
		cp.SeqScalingListPresentFlags = make([]bool, len(o.SeqScalingListPresentFlags))
		copy(cp.SeqScalingListPresentFlags, o.SeqScalingListPresentFlags)
	}
	return cp
}
