// generated by deep-copy -o sps_deepcopy.go --type SPS .; DO NOT EDIT.

package h264parse

// DeepCopy generates a deep copy of SPS
func (o SPS) DeepCopy() SPS {
	var cp SPS = o
	if o.OffsetForRefFrames != nil {
		cp.OffsetForRefFrames = make([]int64, len(o.OffsetForRefFrames))
		copy(cp.OffsetForRefFrames, o.OffsetForRefFrames)
	}
	return cp
}
